# Generated by Django 2.1.5 on 2019-04-27 12:48

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetails',
            fields=[
                ('clientid', models.IntegerField(default=0, primary_key=True, serialize=False, unique=True)),
                ('Company', models.CharField(default='Not a company', max_length=100)),
                ('email', models.EmailField(max_length=30)),
                ('fname', models.CharField(max_length=50)),
                ('lname', models.CharField(max_length=50)),
                ('address', models.CharField(default='Address not available', max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
    ]
