# Generated by Django 2.1.5 on 2019-04-27 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientDetails',
            new_name='ClientDetail',
        ),
    ]
