# Generated by Django 2.1.5 on 2019-04-27 12:52

import admindash.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0002_auto_20190427_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='clientid',
            field=models.IntegerField(default=admindash.models.autoincremet, primary_key=True, serialize=False, unique=True),
        ),
    ]
