# Generated by Django 2.1.5 on 2019-04-27 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0003_auto_20190427_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='country',
            field=models.IntegerField(),
        ),
    ]
