# Generated by Django 2.1.5 on 2019-04-27 13:16

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0004_auto_20190427_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='pincode',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
