# Generated by Django 2.1.5 on 2019-04-27 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0005_auto_20190427_1846'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientdetail',
            old_name='Company',
            new_name='company',
        ),
    ]
