# Generated by Django 2.1.5 on 2019-04-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0006_auto_20190427_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='address',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientdetail',
            name='company',
            field=models.CharField(default='', max_length=100),
        ),
    ]
