# Generated by Django 2.1.5 on 2019-04-27 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0007_auto_20190427_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientdetail',
            name='phone',
            field=models.IntegerField(default=None),
        ),
    ]
