# Generated by Django 2.1.5 on 2019-04-27 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0008_clientdetail_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='pincode',
            field=models.IntegerField(default='0000000000'),
        ),
    ]
