# Generated by Django 2.1.5 on 2019-04-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0010_auto_20190427_2212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
