# Generated by Django 2.1.5 on 2019-04-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0012_auto_20190427_2215'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientdetail',
            name='phonenum',
        ),
    ]
