# Generated by Django 2.1.5 on 2019-04-27 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0014_clientdetail_phonenum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='phonenum',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
    ]
