# Generated by Django 2.1.5 on 2019-04-28 03:52

import admindash.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0015_auto_20190427_2220'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oderid', models.CharField(default=admindash.models.autoincremetorder, max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.ClientDetail')),
            ],
        ),
    ]
