# Generated by Django 2.1.5 on 2019-04-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0016_orderdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='billing',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='data',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='production',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='shipping',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderdetail',
            name='template',
            field=models.BooleanField(default=False),
        ),
    ]
