# Generated by Django 2.1.5 on 2019-04-28 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0018_auto_20190428_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='oderid',
            new_name='orderid',
        ),
    ]
