# Generated by Django 2.1.5 on 2019-04-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0019_auto_20190428_1438'),
    ]

    operations = [
        migrations.CreateModel(
            name='uploadtemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='static/template/main.jpg', upload_to='static/template/')),
                ('orderid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail')),
            ],
        ),
    ]
