# Generated by Django 2.1.5 on 2019-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0021_auto_20190428_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientdetail',
            name='company',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
