# Generated by Django 2.1.5 on 2019-04-28 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0022_auto_20190428_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='bimage',
            field=models.ImageField(default='static/template/demo2.jpg', upload_to='static/template/'),
        ),
        migrations.AlterField(
            model_name='uploadtemplate',
            name='fimage',
            field=models.ImageField(default='static/template/demo1.jpg', upload_to='static/template/'),
        ),
    ]
