# Generated by Django 2.1.5 on 2019-04-28 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0023_auto_20190428_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='orderid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail', unique=True),
        ),
    ]
