# Generated by Django 2.1.5 on 2019-04-29 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0024_auto_20190428_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadtemplate',
            name='response',
            field=models.BooleanField(default=False),
        ),
    ]
