# Generated by Django 2.1.5 on 2019-04-29 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0025_uploadtemplate_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadtemplate',
            name='orderid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail'),
        ),
    ]
