# Generated by Django 2.1.5 on 2019-04-29 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0026_auto_20190429_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(blank=True, upload_to='static/files/')),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail')),
            ],
        ),
    ]
