# Generated by Django 2.1.5 on 2019-05-01 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0027_getdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Barcode Encoding', 'Barcode Encoding'), ('Magnetic Stripe', 'Magnetic Stripe'), ('RFID Encoding', 'RFID Encoding'), ('Proximity-Card', 'Proximity-Card')], max_length=50)),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail')),
            ],
        ),
    ]
