# Generated by Django 2.1.5 on 2019-05-01 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0031_auto_20190501_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.IntegerField(choices=[(199, 'Barcode Encoding'), (399, 'Magnetic Stripe'), (699, 'RFID Encoding'), (799, 'Proximity-Card')], default=0),
        ),
    ]
