# Generated by Django 2.1.5 on 2019-05-01 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0032_auto_20190501_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='type',
            field=models.IntegerField(choices=[(0, 'No response'), (199, 'Barcode Encoding'), (399, 'Magnetic Stripe'), (699, 'RFID Encoding'), (799, 'Proximity-Card')]),
        ),
    ]
