# Generated by Django 2.1.5 on 2019-05-01 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0034_auto_20190501_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='send',
            field=models.BooleanField(default=False),
        ),
    ]
