# Generated by Django 2.1.5 on 2019-05-01 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0035_bill_send'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='admindash.OrderDetail')),
            ],
        ),
    ]
