# Generated by Django 2.1.5 on 2019-05-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0036_productionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstatus',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
