# Generated by Django 2.1.5 on 2019-05-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admindash', '0037_productionstatus_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionstatus',
            name='proceed',
            field=models.BooleanField(default=False),
        ),
    ]
